---

- name: Install missing packages
  apt: name={{ item }} state=present
  with_items:
  - gcc
  - libtool
  - autoconf

- name: Create proxy directory
  action: file path={{ deploy_base }}/{{ proxy_name }}-{{ proxy_version }} state=directory

- name: Retrieve twemproxy
  git: repo=https://github.com/twitter/twemproxy.git dest={{ deploy_base }}/{{ proxy_name }}-{{ proxy_version}} version={{ proxy_version }} force=yes
  #git: repo=https://git.oschina.net/Pythell/twemproxy.git dest={{ deploy_base }}/{{ proxy_name }}-{{ proxy_version}} version={{ proxy_version }} force=yes

- name: Create symlink
  action: file path={{ deploy_base }}/{{ proxy_name }} src={{ deploy_base }}/{{ proxy_name }}-{{ proxy_version }} state=link

- name: Compile
  shell: cd {{ deploy_base }}/{{ proxy_name }} && autoreconf -fvi && ./configure && make && touch installed_ok creates={{ deploy_base }}/{{ proxy_name }}/installed_ok

- name: Copy nutcracker to /usr/bin
  action: shell cp {{ deploy_base }}/{{ proxy_name }}/src/{{ proxy_name }} {{ exec_dir }}/{{ proxy_name }} creates={{ exec_dir }}/{{ proxy_name }}

- name: Create var dirs
  action: file path={{ item }} owner=redis group=redis state=directory
  with_items:
  - /var/log/twemproxy
  - /var/run/twemproxy

- name: Create settings
  template: src={{ proxy_name }}.yml.j2 dest={{ deploy_base }}/{{ proxy_name }}/{{ proxy_name }}.yml owner=redis group=redis mode=0644
  tags: configuration

- name: Install upstart config
  template: src=twemproxy.upstart.j2 dest=/etc/init.d/twemproxy mode=0755

- name: Add to service
  action: shell update-rc.d twemproxy defaults

- name: Enable service
  service: name=twemproxy enabled=yes

- name: Stop twemproxy
  service: name=twemproxy state=stopped

- name: Start twemproxy
  service: name=twemproxy state=started
